image: node:10.16.3

cache:
  paths:
    - node_modules/

before_script:
  - CI=false npm install

pages:
  stage: deploy
  script:
    - npm install
    - npm install react
    - npm install react-dom
    - CI=false npm run build
    - cp dist/bundle.js public
    - cp dist/index.html public
  artifacts:
    paths:
      - public
  only:
    - master